name: test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Allow modern Yarn
        run: |
          corepack enable
      - name: Install dependencies
        run: |
          yarn
      - name: Install cli
        run: cd cli && yarn && yarn build && cd ..
      - name: Check Links
        run: |
          yarn lint:links
      - name: Format Wiki
        run: |
          yarn format:check
