name: deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    strategy:
      matrix:
        environment: [iota, shimmer, next]
    uses: ./.github/workflows/build.reusable.yaml
    with:
      environment: ${{ matrix.environment }}
      ref: ''
  config:
    uses: ./.github/workflows/config.reusable.yaml
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - config
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # All previous jobs upload to same artifact so only a single download required
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
      # Paths of the build artifacts are preserved (`build`, `build/shimmer`, and `build/next`)
      - name: Extract build
        run: |
          tar -xf iota.tar
          tar -xf shimmer.tar
          tar -xf next.tar
      # Convert to Vercel project and upload
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      # Trigger Algolia crawler
      - name: Crawl
        run: |
          curl -H "Content-Type: application/json" -X POST --user ${{ secrets.ALGOLIA_USER_ID }}:${{ secrets.ALGOLIA_API_KEY }} "https://crawler.algolia.com/api/1/crawlers/${{ secrets.ALGOLIA_CRAWLER_ID }}/run"
