name: deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=3072'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for showLastUpdateTime to work
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Allow modern Yarn
        run: |
          corepack enable
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn build:production
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: 'github-action[bot]'
          user_email: 'github-action[bot]@noreply@github.com'
          cname: wiki.iota.org
