name: deploy

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  checks:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Build
        run: |
          yarn install --immutable
          yarn build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    env:
      BUILD: '*/*/documentation'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for showLastUpdateTime to work
      - name: Init and update submodules
        run: |
          git submodule update --init --recursive --remote
      - name: Install dependencies
        run: |
          yarn install
      - name: Add external doc config
        run: |
          yarn cli start
      - name: Checkout external docs
        run: |
          yarn cli checkout --no-overwrite
      - name: Build
        run: |
          yarn build
      - name: Release to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: wiki.iota.org
