name: preview pr
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [iota, shimmer, next]
    env:
      NODE_OPTIONS: '--max-old-space-size=3072'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for showLastUpdateTime to work
      - name: Cache submodules
        uses: actions/cache@v3
        with:
          path: |
            */external
            .git/modules
          key: ${{ runner.os }}-wiki-submodules-${{ hashFiles('.gitmodules') }}
          restore-keys: |
            ${{ runner.os }}-wiki-submodules
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Allow modern Yarn
        run: |
          corepack enable
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .git/modules
          key: ${{ runner.os }}-wiki-dependencies-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-wiki-dependencies
      - name: Install dependencies
        run: |
          yarn
      - name: Cache Docusaurus artifacts
        uses: actions/cache@v3
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-${{ matrix.environment }}-wiki-build-${{ hashFiles('package.json', 'yarn.lock', 'src/**/*.*') }}
      - name: Build Docusaurus artifacts
        run: |
          yarn vercel:${{ matrix.environment }}
      - name: Create Docusaurus artifacts archive
        run: |
          tar -cf ${{ matrix.environment }}.tar build
      - name: Upload Docusaurus artifacts archive
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ${{ matrix.environment }}.tar
  config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload Vercel config
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: vercel.json
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - config
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      - name: Extract Docusaurus artifacts archives
        run: |
          tar -xf iota.tar
          tar -xf shimmer.tar
          tar -xf next.tar
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
