name: preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
  pull_request:
    types: [ready_for_review]
    branches: [main]
  issue_comment:
    types: [created]

jobs:
  build:
    if: |
      github.actor != 'dependabot[bot]' &&
      (
        github.event.pull_request || 
        (
          github.event.issue.pull_request && 
          contains(github.event.comment.body, '/create-preview')
        )
      )
    strategy:
      matrix:
        environment: [iota, shimmer, next]
    uses: ./.github/workflows/build.reusable.yaml
    with:
      environment: ${{ matrix.environment }}
  config:
    needs: [build]
    uses: ./.github/workflows/config.reusable.yaml
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - config
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # All previous jobs upload to same artifact so only a single download required
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
      # Paths of the build artifacts are preserved (`build`, `build/shimmer`, and `build/next`)
      - name: Extract build
        run: |
          tar -xf iota.tar
          tar -xf shimmer.tar
          tar -xf next.tar
      # Convert to Vercel project and upload
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          PR_LABELS: false
          PREBUILT: true
          PRODUCTION: false
          GITHUB_DEPLOYMENT_ENV: Preview
