name: publish packages

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    strategy:
      matrix:
        package: [core, cli]
        include:
          - package: core
            path: 'package.json'
            workspace: '@iota-wiki/core'
          - package: cli
            path: 'cli/package.json'
            workspace: '@iota-wiki/cli'
    uses: ./.github/workflows/publish.reusable.yaml
    with:
      path: ${{ matrix.path }}
      workspace: ${{ matrix.workspace }}
