name: Publish
on: push
jobs:
  version-changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: cli
        id: cli
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          assume-same-version: new
          file-name: ./cli/package.json
    outputs:
      cli: ${{ steps.cli.outputs.changed }}
  publish-cli:
    runs-on: ubuntu-latest
    needs: version-changed
    if: needs.version-changed.outputs.cli == 'true'
    env:
      IS_MAIN: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Allow modern Yarn
        run: |
          corepack enable
      - name: Install dependencies
        run: |
          yarn install
      # Publish to NMP
      - uses: actions/setup-node@v3
      - name: Publish to NPM
        run: |
          if [ "$IS_MAIN" = true ]; then
            yarn workspace @iota-wiki/cli npm publish --access public --tolerate-republish
          else
            yarn workspace @iota-wiki/cli npm publish --access public --tag experimental
          fi
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://registry.npmjs.org'
      # Publish to GitHub
      - uses: actions/setup-node@v3
      - name: Publish to GitHub
        run: |
          if [ "$IS_MAIN" = true ]; then
            yarn workspace @iota-wiki/cli npm publish --access public --tolerate-republish
          else
            yarn workspace @iota-wiki/cli npm publish --access public --tag experimental
          fi
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://npm.pkg.github.com'
