name: Publish
on: push
jobs:
  version:
    # Check if core or cli versions changed and output metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: core
        id: core
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          assume-same-version: new
          file-name: ./package.json
      - name: cli
        id: cli
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          assume-same-version: new
          file-name: ./cli/package.json
    outputs:
      core-changed: ${{ steps.core.outputs.changed }}
      core-version: ${{ steps.core.outputs.version }}
      cli-changed: ${{ steps.cli.outputs.changed }}
      cli-version: ${{ steps.cli.outputs.version }}
  publish-core:
    # If not on main and version changed, publish with experimental tag
    runs-on: ubuntu-latest
    needs: version
    if: github.ref != 'refs/heads/main' && needs.version.outputs.core-changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Allow modern Yarn
        run: |
          corepack enable
      - name: Install dependencies
        run: |
          yarn install
      # Publish to NMP
      - name: Publish to NPM
        run: |
          yarn npm publish --access public --tag experimental
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://registry.npmjs.org'
      # Publish to GitHub
      - name: Publish to GitHub
        run: |
          yarn npm publish --access public --tag experimental
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://npm.pkg.github.com'
  publish-cli:
    # If not on main and version changed, publish with experimental tag
    runs-on: ubuntu-latest
    needs: version
    if: github.ref != 'refs/heads/main' && needs.version.outputs.cli-changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Allow modern Yarn
        run: |
          corepack enable
      - name: Install dependencies
        run: |
          yarn install
      # Publish to NMP
      - name: Publish to NPM
        run: |
          yarn workspace @iota-wiki/cli npm publish --access public --tag experimental
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://registry.npmjs.org'
      # Publish to GitHub
      - name: Publish to GitHub
        run: |
          yarn workspace @iota-wiki/cli npm publish --access public --tag experimental
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://npm.pkg.github.com'
  tag-core:
    # If on main and version changed, change tag to latest
    runs-on: ubuntu-latest
    needs: version
    if: github.ref == 'refs/heads/main' && needs.version.outputs.core-changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Allow modern Yarn
        run: |
          corepack enable
      # Tag on NMP
      - name: Publish to NPM
        run: |
          yarn npm tag add @iota-wiki/core@${{ needs.version.outputs.core-version }} latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://registry.npmjs.org'
      # Tag on GitHub
      - name: Publish to GitHub
        run: |
          yarn npm tag add @iota-wiki/core@${{ needs.version.outputs.core-version }} latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://npm.pkg.github.com'
  tag-cli:
    # If on main and version changed, change tag to latest
    runs-on: ubuntu-latest
    needs: version
    if: github.ref == 'refs/heads/main' && needs.version.outputs.cli-changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Allow modern Yarn
        run: |
          corepack enable
      # Tag on NMP
      - name: Publish to NPM
        run: |
          yarn npm tag add @iota-wiki/cli@${{ needs.version.outputs.cli-version }} latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://registry.npmjs.org'
      # Tag on GitHub
      - name: Publish to GitHub
        run: |
          yarn npm tag add @iota-wiki/cli@${{ needs.version.outputs.cli-version }} latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://npm.pkg.github.com'
