name: tag packages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  version:
    # Check if core or cli versions changed and output metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      # Check if core changed
      - name: Check @iota-wiki/core changed in current branch
        id: core-to-current
        uses: EndBug/version-check@v2
        with:
          file-name: ./package.json
          diff-search: true
          # Only compare before and after if before exists, else check commits
          file-url: ${{ github.event.before && '::before' }}
          static-checking: ${{ github.event.before && 'localIsNew' }}
      # Check if cli changed
      - name: Check @iota-wiki/cli changed in current branch
        id: cli-to-current
        uses: EndBug/version-check@v2
        with:
          file-name: ./cli/package.json
          diff-search: true
          # Only compare before and after if before exists, else check commits
          file-url: ${{ github.event.before && '::before' }}
          static-checking: ${{ github.event.before && 'localIsNew' }}
    outputs:
      core-changed: ${{ steps.core-to-current.outputs.changed }}
      core-version: ${{ steps.core-to-current.outputs.version }}
      cli-changed: ${{ steps.cli-to-current.outputs.changed }}
      cli-version: ${{ steps.cli-to-current.outputs.version }}
  tag-core:
    # If version changed, change tag to latest
    runs-on: ubuntu-latest
    needs: version
    if: needs.version.outputs.core-changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Allow modern Yarn
        run: |
          corepack enable
      # Tag on NMP
      - name: Publish to NPM
        run: |
          yarn npm tag add @iota-wiki/core@${{ needs.version.outputs.core-version }} latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://registry.npmjs.org'
      # Tag on GitHub
      - name: Publish to GitHub
        run: |
          yarn npm tag add @iota-wiki/core@${{ needs.version.outputs.core-version }} latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://npm.pkg.github.com'
  tag-cli:
    # If version changed, change tag to latest
    runs-on: ubuntu-latest
    needs: version
    if: needs.version.outputs.cli-changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Allow modern Yarn
        run: |
          corepack enable
      # Tag on NMP
      - name: Publish to NPM
        run: |
          yarn npm tag add @iota-wiki/cli@${{ needs.version.outputs.cli-version }} latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://registry.npmjs.org'
      # Tag on GitHub
      - name: Publish to GitHub
        run: |
          yarn npm tag add @iota-wiki/cli@${{ needs.version.outputs.cli-version }} latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://npm.pkg.github.com'
