name: tag packages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tag:
    strategy:
      matrix:
        package: [core, cli]
        include:
          - package: core
            path: 'package.json'
            workspace: '@iota-wiki/core'
          - package: cli
            path: 'cli/package.json'
            workspace: '@iota-wiki/cli'
    uses: ./.github/workflows/tag.reusable.yaml
    with:
      path: ${{ matrix.path }}
      workspace: ${{ matrix.workspace }}
