name: test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  consistency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Allow modern Yarn
        run: |
          corepack enable
      - name: Install dependencies
        run: |
          yarn
      - name: Lint Wiki
        run: |
          yarn lint:check
      - name: Format Wiki
        run: |
          yarn format:check
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        uses: ./.github/actions/prepare/
      - name: Checkout remote
        run: yarn checkout:remote
      - name: Build
        run: yarn build
