name: test-build
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        environment: [iota, shimmer, next]
    uses: ./.github/workflows/build.reusable.yaml
    with:
      environment: ${{ matrix.environment }}
      ref: ''
