name: test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CONTENT: '*/*/*/documentation,*/*/*,*/*'
      NODE_OPTIONS: '--max-old-space-size=3072'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for showLastUpdateTime to work
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Allow modern Yarn
        run: |
          corepack enable
      - name: Init and update submodules
        run: |
          git submodule update --init --recursive
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn build
